# Generated by Django 5.1.3 on 2024-12-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mobilemoneypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneypayment',
            name='delivery_option',
        ),
    ]
