# Generated by Django 5.1.3 on 2024-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_mobilemoneypayment_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneypayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('validated', 'Validé')], default='pending', max_length=10),
        ),
    ]
