# Generated by Django 5.1.3 on 2024-12-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mobilemoneypayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneypayment',
            name='status',
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='delivery_option',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
