from django.urls import path
from . import views

urlpatterns = [
    path('signup',views.signup, name='signup'),
    path('signin',views.signin, name='signin'),
    path('signout',views.signout, name='signout'),
    path('profile',views.profile, name='profile'),
    path('update_profile',views.update_profile, name='update_profile'),
    path('store/create/', views.create_store, name='create_store'),
    path('store/edit/<slug:slug>/', views.edit_store, name='edit_store'),  # Use slug
    path('store/delete/<slug:slug>/', views.delete_store, name='delete_store'),
    path('store/<int:store_id>/', views.store_detail, name='store_detail'),
    path('store/<int:pk>/add_testimonial/', views.TestimonialCreateView.as_view(), name='add_testimonial'),
    path('store/<slug:slug>/create-category/', views.create_category, name='create_category'),
    path('store/<slug:slug>/category/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('store/<int:store_id>/categories/', views.list_categories, name='list_categories'),
    path('store/<int:store_id>/product/create/', views.create_product, name='create_product'),
    path('store/<slug:slug>/products/', views.manage_product_store, name='manage_product_store'),
    path('product/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_photo/<int:photo_id>/', views.delete_photo, name='delete_photo'),
    path('product/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    # path('cart/', views.cart_detail, name='cart_detail'),
    # path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:cart_item_id>/<int:quantity>/', views.update_cart, name='update_cart'),
    path('cart/remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('store/<slug:slug>/', views.store_detail, name='store_detail'),
    path('store/<slug:slug>/create_category/', views.create_category, name='create_category'),
    path('store/<slug:slug>/create_product/', views.create_product, name='create_product'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('ajouter-au-panier/<int:product_id>/', views.add_to_cart_ajax, name='add_to_cart_ajax'),
    path('add-to-cart-success/', views.add_to_cart_success, name='add_to_cart_success'),
    path('panier/', views.cart_detail, name='cart_detail'),
    path('get-cart-items-count/', views.get_cart_items_count, name='get_cart_items_count'),
    path('store/<slug:slug>/add_testimonial/', views.add_testimonial, name='add_testimonial'),
    path('product/<int:id>/add_testimonialproduct/', views.add_testimonialproduct, name='add_testimonialproduct'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_cancel/', views.payment_cancel, name='payment_cancel'),
    path('order/<int:order_id>/detail/', views.order_detail, name='order_detail'),
    path('store/<slug:slug>/orders/<str:order_date>/', views.orders_by_date_detail, name='orders_by_date_detail'),
    path('orders/<int:order_id>/', views.order_detail_store, name='order_detail_store'),
    path('mobile-money-checkout/', views.mobile_money_checkout, name='mobile_money_checkout'),
    path('mobile-money/waiting/<int:payment_id>/', views.mobile_money_waiting, name='mobile_money_waiting'),
    path('mobile-money-payment-success/', views.mobile_money_payment_success, name='mobile_money_payment_success'),
    path('creer-commande/', views.creer_commande, name='creer_commande'),
    path('livraison/<int:commande_id>/', views.livraison_detail, name='livraison_detail'),
]

